apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-controller-manager-operator
  namespace: openshift-kube-controller-manager-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  groups:
    - name: cluster-version
      rules:
        - alert: KubeControllerManagerDown
          annotations:
            summary: Target disappeared from Prometheus target discovery.
            description: KubeControllerManager has disappeared from Prometheus target discovery.
          expr: |
            absent(up{job="kube-controller-manager"} == 1)
          for: 15m
          labels:
            severity: critical
            namespace: openshift-kube-controller-manager
        - alert: PodDisruptionBudgetAtLimit
          annotations:
            summary: The pod disruption budget is preventing further disruption to pods.
            description: The pod disruption budget is at minimum disruptions allowed level. The number of current healthy pods is equal to desired healthy pods.
          expr: |
            max by(namespace, poddisruptionbudget) (kube_poddisruptionbudget_status_current_healthy == kube_poddisruptionbudget_status_desired_healthy and on (namespace, poddisruptionbudget) kube_poddisruptionbudget_status_expected_pods > 0)
          for: 60m
          labels:
            severity: warning
        - alert: PodDisruptionBudgetLimit
          annotations:
            summary: The pod disruption budget registers insufficient amount of pods.
            description: The pod disruption budget is below minimum disruptions allowed level and is not satisfied. The number of current healthy pods is less than then desired healthy pods.
          expr: |
            max by (namespace, poddisruptionbudget) (kube_poddisruptionbudget_status_current_healthy < kube_poddisruptionbudget_status_desired_healthy)
          for: 15m
          labels:
            severity: critical
