apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openshift-kube-controller-manager
  name: system:openshift:leader-election-lock-cluster-policy-controller
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  resourceNames:
  - cluster-policy-controller-lock
  verbs:
  - get
  - create
  - update
