apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:kube-controller-manager:vsphere-legacy-cloud-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:kube-controller-manager:vsphere-legacy-cloud-provider
subjects:
  - kind: ServiceAccount
    name: vsphere-legacy-cloud-provider
    namespace: kube-system
